"""add fingerprint column

Revision ID: 4021139c47d4
Revises: be8c1efe075a
Create Date: 2026-02-20 19:38:15.132693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4021139c47d4'
down_revision: Union[str, None] = 'be8c1efe075a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('fingerprint', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_incidents_fingerprint'), 'incidents', ['fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_fingerprint'), table_name='incidents')
    op.drop_column('incidents', 'fingerprint')
    # ### end Alembic commands ###
