"""create incidents

Revision ID: 83983b9ab3b4
Revises: 
Create Date: 2026-02-20 18:28:17.548344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83983b9ab3b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('line_id', sa.String(length=64), nullable=True),
    sa.Column('line_name', sa.String(length=128), nullable=True),
    sa.Column('station_id', sa.String(length=64), nullable=True),
    sa.Column('station_name', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('reason_text', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lng', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_line_id'), 'incidents', ['line_id'], unique=False)
    op.create_index(op.f('ix_incidents_occurred_at'), 'incidents', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_incidents_source'), 'incidents', ['source'], unique=False)
    op.create_index(op.f('ix_incidents_station_id'), 'incidents', ['station_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_station_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_source'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_occurred_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_line_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
